"""initial migrations

Revision ID: 90a533d17a10
Revises:
Create Date: 2025-10-20 19:55:00.095717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '90a533d17a10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_table('rag_sparse_retriever')
    op.drop_table('rag_prompt')
    op.drop_table('rag_document_pipeline_session_link')
    op.drop_table('rag_embedding_matrix')
    op.drop_table('rag_retriever')
    op.drop_table('document')
    op.drop_table('rag_generation_model')
    op.drop_table('rag_chunking_model')
    op.drop_table('rag_embedding_model')
    op.drop_table('rag_dense_retriever')
    op.drop_table('rag_pipeline')
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastest_version', sa.String(), nullable=False))
        batch_op.drop_column('latest_version')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_version', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('lastest_version')

    op.create_table('rag_pipeline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('chunking_model_id', sa.INTEGER(), nullable=False),
    sa.Column('retriever_model_id', sa.INTEGER(), nullable=False),
    sa.Column('prompt_id', sa.INTEGER(), nullable=False),
    sa.Column('generation_model_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_model_id'], ['rag_generation_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['rag_prompt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retriever_model_id'], ['rag_retriever.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_dense_retriever',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('embedding_model_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['rag_embedding_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_embedding_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunking_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_generation_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(), nullable=False),
    sa.Column('optional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('last_modified', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('rag_retriever',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('dense_retriever_id', sa.INTEGER(), nullable=True),
    sa.Column('sparse_retriever_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("(class_name = 'SparseRetriever' AND sparse_retriever_id IS NOT NULL AND dense_retriever_id IS NULL) OR (class_name = 'DenseRetriever' AND dense_retriever_id IS NOT NULL AND sparse_retriever_id IS NULL)", name='chk_retriever_type'),
    sa.ForeignKeyConstraint(['dense_retriever_id'], ['rag_dense_retriever.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sparse_retriever_id'], ['rag_sparse_retriever.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_embedding_matrix',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('chunking_model_id', sa.INTEGER(), nullable=False),
    sa.Column('embedding_model_id', sa.INTEGER(), nullable=False),
    sa.Column('storage_folder', sa.VARCHAR(), nullable=False),
    sa.Column('matrix_shape', sqlite.JSON(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('last_modified', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['rag_embedding_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunking_model_id', 'embedding_model_id', name=op.f('uix_document_chunking_embedding'))
    )
    op.create_table('rag_document_pipeline_session_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('pipeline_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['rag_pipeline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'pipeline_id', name=op.f('uix_document_pipeline')),
    sa.UniqueConstraint('document_id', 'session_id', name=op.f('uix_document_session')),
    sa.UniqueConstraint('session_id', 'pipeline_id', name=op.f('uix_session_pipeline'))
    )
    op.create_table('rag_prompt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_sparse_retriever',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('storage_folder', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('chunking_model_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('hash', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('id', 'document_id', name=op.f('uix_chunk_document'))
    )
    # ### end Alembic commands ###
